package io.github.aratakileo.elegantia

import org.gradle.api.Project
import org.jetbrains.annotations.NotNull

class AccessFileGenerator {
    private final static String FORGE_MODIFIER = "public-f"

    private final List<Project> inputProjects
    private final Project project
    private final String modId
    private final File outputDir
    private final File metaInfDir
    private final boolean genForge
    private final boolean genFabric

    AccessFileGenerator(
            @NotNull Project outputProject,
            @NotNull List<Project> inputProjects,
            boolean genForge = true,
            boolean genFabric = true
    ) {
        this.project = outputProject
        this.inputProjects = inputProjects

        this.modId = outputProject.findProperty("mod_id")
        this.outputDir = outputProject.layout.buildDirectory.file("${Constants.Dirs.GENERATED_RESOURCES}").get().asFile
        this.metaInfDir = new File(outputDir, "META-INF")

        this.genForge = genForge
        this.genFabric = genFabric
    }

    void generate() {
        if (!outputDir.exists()) outputDir.mkdirs()
        if (!metaInfDir.exists()) metaInfDir.mkdirs()

        final var resourcesDir = project.file(Constants.Dirs.MAIN_RESOURCES)

        final var combinedAwLines = [
                "accessWidener v2 named",
                "\n####################################",
                "# generated by Elegantia Gradle :)",
                "####################################\n"
        ] as List<String>


        inputProjects.forEach {proj ->
            proj.fileTree(Constants.Dirs.MAIN_RESOURCES).matching {
                include "**/*.accesswidener"
            }.each { file ->
                combinedAwLines.add("# file ${Utils.normalizeSlashes(resourcesDir.toPath().relativize(file.toPath()))}")

                file.eachLine { line ->
                    if (line.isBlank() || line.stripLeading().startsWith("#") || line.startsWith("accessWidener")) return

                    combinedAwLines.add(line)
                }

                combinedAwLines.add('')
            }
        }

        if (genFabric) new File(outputDir, "${modId}.accesswidener").text = combinedAwLines.join("\n")
        if (genForge) generateForgeFile(combinedAwLines)
    }

    private void generateForgeFile(@NotNull List<String> awLines) {
        final var atLines = [] as List<String>

        awLines.each { line ->
            if (line.stripLeading().startsWith("accessWidener")) return

            if (line.stripLeading().startsWith("#") || line.isBlank()) {
                atLines.add(line)
                return
            }

            final var parts = line.tokenize('\t ')

            if (parts.size() < 3) return

            final var type = parts[1]
            final var target = parts[2]

            if (type == "class") atLines.add "${FORGE_MODIFIER} ${target.replace('/', '.')}"
            else if (type == "field" || type == "method") {
                if (parts.size() >= 4) {
                    final var className = target.replace('/', '.')
                    final var memberName = parts[3]

                    atLines.add "${FORGE_MODIFIER} ${className} ${memberName}${type == 'method' ? parts[4] : ''}"
                }
            }
        }

        new File(metaInfDir, "accesstransformer.cfg").text = atLines.join("\n")
    }
}
